"""create_initial_travel_platform_tables

Revision ID: 01457c09e266
Revises: 
Create Date: 2026-09-26 20:52:14.855487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01457c09e266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinations_name'), ['name'], unique=False)

    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('starting_city', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.SmallInteger(), nullable=False),
    sa.Column('duration_nights', sa.SmallInteger(), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hotel_info', sa.Text(), nullable=True),
    sa.Column('meals_info', sa.Text(), nullable=True),
    sa.Column('transportation_info', sa.Text(), nullable=True),
    sa.Column('sightseeing_info', sa.Text(), nullable=True),
    sa.Column('activities_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_days > 0', name='ck_packages_duration_days_positive'),
    sa.CheckConstraint('duration_nights >= 0', name='ck_packages_duration_nights_non_negative'),
    sa.CheckConstraint('price_per_person >= 0', name='ck_packages_price_non_negative'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_duration_days'), ['duration_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_price_per_person'), ['price_per_person'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_starting_city'), ['starting_city'], unique=False)

    op.create_table('package_availability_months',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_availability_month_range'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'month')
    )
    with op.batch_alter_table('package_availability_months', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_availability_months_month'), ['month'], unique=False)

    op.create_table('package_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_exclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_exclusions_package_id'), ['package_id'], unique=False)

    op.create_table('package_inclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_inclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_inclusions_package_id'), ['package_id'], unique=False)

    op.create_table('package_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('accommodation', sa.String(length=255), nullable=True),
    sa.Column('meals_provided', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'day_number', name='uq_package_itinerary_day')
    )
    with op.batch_alter_table('package_itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_itineraries_package_id'), ['package_id'], unique=False)

    op.create_table('package_themes',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'theme_id')
    )
    with op.batch_alter_table('package_themes', schema=None) as batch_op:
        batch_op.create_index('idx_package_themes_theme_id', ['theme_id'], unique=False)

    op.create_table('package_travel_types',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('travel_type', sa.Enum('Solo', 'Couple', 'Family', 'Group', name='travel_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'travel_type')
    )
    with op.batch_alter_table('package_travel_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_travel_types_travel_type'), ['travel_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_travel_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_travel_types_travel_type'))

    op.drop_table('package_travel_types')
    with op.batch_alter_table('package_themes', schema=None) as batch_op:
        batch_op.drop_index('idx_package_themes_theme_id')

    op.drop_table('package_themes')
    with op.batch_alter_table('package_itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_itineraries_package_id'))

    op.drop_table('package_itineraries')
    with op.batch_alter_table('package_inclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_inclusions_package_id'))

    op.drop_table('package_inclusions')
    with op.batch_alter_table('package_exclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_exclusions_package_id'))

    op.drop_table('package_exclusions')
    with op.batch_alter_table('package_availability_months', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_availability_months_month'))

    op.drop_table('package_availability_months')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_starting_city'))
        batch_op.drop_index(batch_op.f('ix_packages_price_per_person'))
        batch_op.drop_index(batch_op.f('ix_packages_operator_id'))
        batch_op.drop_index(batch_op.f('ix_packages_duration_days'))
        batch_op.drop_index(batch_op.f('ix_packages_destination_id'))

    op.drop_table('packages')
    op.drop_table('themes')
    op.drop_table('operators')
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_name'))

    op.drop_table('destinations')
    # ### end Alembic commands ###
